# Advent of Code 2020 - Puzzle 3A

## Import packages

In [2]:
import pandas as pd

## Constants

In [3]:
start_hor_coordinate = 0
start_vert_coordinate = 0
fly_right = 3
fly_down = 1

## Load data

In [4]:
data = pd.read_csv("data/input_puzzle_3.txt", header = None)
data.columns = ['coordinates'] # Add column name
data.head()

                       coordinates
0  .........#.#.#.........#.#.....
1  ...#......#...#.....#.....#....
2  #.....#.....#.....#.#........#.
3  ......#..#......#.......#......
4  .#..........#.............#...#

## Functions

In [5]:
def split(word): 
    return [char for char in word]

In [6]:
def hitAlmostTree(coordinates_map, x, y):
    if (coordinates_map.iloc[x, y] == "#"):
        return True
    else:
        return False

## Make coordinates map

In [7]:
# Calculate the number of coordinates:
total_hor_coordinates = len(data['coordinates'].iloc[0])
total_vert_coordinates = len(data)

In [8]:
# New data frame with split value columns 
coordinates_map = data["coordinates"].str.split("", n = total_hor_coordinates, expand = True)
coordinates_map.drop(0, axis = 1, inplace = True)
coordinates_map.columns = [list(range(0, total_hor_coordinates))]
coordinates_map

    0  1  2  3  4  5  6  7  8  9   ... 21 22 23 24 25 26 27 28 29 30
0    .  .  .  .  .  .  .  .  .  #  ...  .  .  #  .  #  .  .  .  .  .
1    .  .  .  #  .  .  .  .  .  .  ...  .  .  .  .  .  #  .  .  .  .
2    #  .  .  .  .  .  #  .  .  .  ...  .  .  .  .  .  .  .  .  #  .
3    .  .  .  .  .  .  #  .  .  #  ...  .  .  .  #  .  .  .  .  .  .
4    .  #  .  .  .  .  .  .  .  .  ...  .  .  .  .  .  #  .  .  .  #
..  .. .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. .. .. ..
318  .  .  .  .  .  .  .  .  .  .  ...  .  .  .  #  .  .  #  .  .  .
319  .  #  #  #  .  .  .  .  .  .  ...  .  .  #  .  .  .  .  .  .  .
320  .  .  .  .  .  #  .  .  .  .  ...  .  .  #  .  .  .  .  .  .  #
321  .  .  #  #  .  .  #  #  .  .  ...  .  .  .  .  .  #  .  #  .  .
322  .  .  .  #  #  #  .  #  .  .  ...  .  .  .  .  .  #  .  .  .  .

[323 rows x 31 columns]

## Main

In [9]:
total_encounterd_trees = 0
route_map = coordinates_map.copy()

# Current start position:
current_vert_coordinate = start_vert_coordinate
current_hor_coordinate = start_hor_coordinate

# Continu untill South Pole is reached:
while current_vert_coordinate < total_vert_coordinates:
    
    if hitAlmostTree(coordinates_map, current_vert_coordinate, current_hor_coordinate) == True:
        total_encounterd_trees += 1
        route_map.iloc[current_vert_coordinate, current_hor_coordinate] = 'X' # tree
    else:
        route_map.iloc[current_vert_coordinate, current_hor_coordinate] = 'O' # open field
    
    # Slope:
    current_vert_coordinate += fly_down
    current_hor_coordinate += fly_right

    # Return to the most left position when right end of the world is reached:
    if current_hor_coordinate >= total_hor_coordinates:
        current_hor_coordinate = current_hor_coordinate - total_hor_coordinates    

print("Total number of encounted trees: ", total_encounterd_trees)

Total number of encounted trees:  282

In [10]:
route_map

    0  1  2  3  4  5  6  7  8  9   ... 21 22 23 24 25 26 27 28 29 30
0    O  .  .  .  .  .  .  .  .  #  ...  .  .  #  .  #  .  .  .  .  .
1    .  .  .  X  .  .  .  .  .  .  ...  .  .  .  .  .  #  .  .  .  .
2    #  .  .  .  .  .  X  .  .  .  ...  .  .  .  .  .  .  .  .  #  .
3    .  .  .  .  .  .  #  .  .  X  ...  .  .  .  #  .  .  .  .  .  .
4    .  #  .  .  .  .  .  .  .  .  ...  .  .  .  .  .  #  .  .  .  #
..  .. .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. .. .. ..
318  .  .  .  .  .  .  .  .  .  .  ...  .  .  .  X  .  .  #  .  .  .
319  .  #  #  #  .  .  .  .  .  .  ...  .  .  #  .  .  .  O  .  .  .
320  .  .  .  .  .  #  .  .  .  .  ...  .  .  #  .  .  .  .  .  .  X
321  .  .  X  #  .  .  #  #  .  .  ...  .  .  .  .  .  #  .  #  .  .
322  .  .  .  #  #  X  .  #  .  .  ...  .  .  .  .  .  #  .  .  .  .

[323 rows x 31 columns]